import { NextResponse } from "next/server";

import { getCanonicalWeekStart, getSubscriptionSummary } from "@/lib/native-subscriptions/store";
import { authenticateNativeSubscriptionRequest } from "@/lib/native-subscriptions/auth";
import { createAdminSupabaseClient } from "@/utils/supabase/admin";
import { createServerSupabaseClient } from "@/utils/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function json(payload: unknown, status = 200) {
  return NextResponse.json(payload, {
    status,
    headers: { "Cache-Control": "private, no-store" },
  });
}

type InsightKind = "score-history" | "manual-activity-trends" | "mood-correlation" | "weekly-report" | "monthly-report";

function asDate(value: Date): string {
  return value.toISOString().slice(0, 10);
}

function buildWeeklyReport(source: {
  mindScore: number | null;
  bodyScore: number | null;
  bondScore: number | null;
  mindWeekChange: number | null;
  bodyWeekChange: number | null;
  bondWeekChange: number | null;
  monthWorkouts: number;
  recommendedAction: string | null;
}) {
  const pillars = [
    { label: "Mind", score: Math.round(source.mindScore ?? 0), change: source.mindWeekChange },
    { label: "Body", score: Math.round(source.bodyScore ?? 0), change: source.bodyWeekChange },
    { label: "Bond", score: Math.round(source.bondScore ?? 0), change: source.bondWeekChange },
  ];
  const moved = pillars.filter((pillar) => pillar.change !== null && Number.isFinite(pillar.change));
  const risen = [...moved].filter((pillar) => (pillar.change ?? 0) > 0).sort((a, b) => (b.change ?? 0) - (a.change ?? 0));
  const fallen = [...moved].filter((pillar) => (pillar.change ?? 0) < 0).sort((a, b) => (a.change ?? 0) - (b.change ?? 0));
  const trainingClause = source.monthWorkouts >= 4 ? "You've been training consistently. " : "";
  let summary: string;
  if (moved.length === 0) summary = "Your scores are here. Week-on-week trends will appear when previous-week data is available.";
  else if (fallen.length > 0 && risen.length > 0) summary = `${trainingClause}You've kept your ${risen[0].label} score moving, but your ${fallen[0].label} score has dipped.`;
  else if (fallen.length > 0) summary = `${trainingClause}Your ${fallen[0].label} score has dipped this week.`;
  else if (risen.length > 0) summary = `${trainingClause}Every pillar you moved this week moved up — ${risen[0].label} most of all.`;
  else summary = `${trainingClause}Your scores held steady this week.`;
  const actionLabels: Record<string, string> = {
    checkin: "Check in with yourself",
    mind_breathing: "Take a two-minute Mind reset",
    body_workout: "Move your body",
    bond_present_mode: "Make time to connect",
  };
  const nextWeek = source.recommendedAction && actionLabels[source.recommendedAction]
    ? `Next week: ${actionLabels[source.recommendedAction]}.`
    : "Next week: Choose one small action that supports your wellbeing.";
  return { pillars, summary, nextWeek };
}

async function getRequestContext(request: Request) {
  if (request.headers.get("authorization")?.match(/^Bearer\s+/i)) {
    const auth = await authenticateNativeSubscriptionRequest(request);
    return auth ? { userId: auth.user.id, admin: auth.admin } : null;
  }
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();
  return user ? { userId: user.id, admin: createAdminSupabaseClient() } : null;
}

export async function GET(request: Request) {
  const context = await getRequestContext(request);
  if (!context) return json({ error: "Sign in required" }, 401);

  try {
    const subscription = await getSubscriptionSummary(context.admin, context.userId);
    if (!subscription.isPro) return json({ error: "Pro required" }, 403);

    const url = new URL(request.url);
    const kind = url.searchParams.get("kind") as InsightKind | null;
    const now = new Date();

    if (kind === "score-history") {
      const { data, error } = await context.admin
        .from("dad_score_history_view")
        .select("week_start,total_score,mind_score,body_score,bond_score,mind_has_data,body_has_data,bond_has_data")
        .eq("user_id", context.userId)
        .order("week_start", { ascending: true });
      if (error) throw error;
      const points = (data ?? []).filter((point) => point.mind_has_data || point.body_has_data || point.bond_has_data);
      return json({ points });
    }

    if (kind === "manual-activity-trends") {
      const { data, error } = await context.admin
        .from("dad_manual_activity_history_view")
        .select("week_start,mind_manual_points,body_manual_points,bond_manual_points")
        .eq("user_id", context.userId)
        .order("week_start", { ascending: true });
      if (error) throw error;
      return json({ points: data ?? [] });
    }

    if (kind === "mood-correlation") {
      // Use the latest week_start generated by the canonical score-history view;
      // this shares PostgreSQL's current_date/session-timezone week boundary.
      const startKey = await getCanonicalWeekStart(context.admin, context.userId);
      const start = new Date(`${startKey}T00:00:00.000Z`);
      const endExclusive = new Date(start);
      endExclusive.setUTCDate(endExclusive.getUTCDate() + 7);
      const [sleepResult, moodResult] = await Promise.all([
        context.admin.from("sleep_logs").select("date,hours").eq("user_id", context.userId).gte("date", asDate(start)).lt("date", asDate(endExclusive)),
        context.admin.from("mood_logs").select("date,mood_value,mood_scale_version").eq("user_id", context.userId).gte("date", asDate(start)).lt("date", asDate(endExclusive)),
      ]);
      if (sleepResult.error) throw sleepResult.error;
      if (moodResult.error) throw moodResult.error;
      const moodByDate = new Map((moodResult.data ?? []).map((row) => [
        String(row.date), Number(row.mood_value) + (row.mood_scale_version === 1 ? 0 : 1),
      ]));
      const pairs = (sleepResult.data ?? []).flatMap((row) => {
        const mood = moodByDate.get(String(row.date));
        const hours = Number(row.hours);
        return mood != null && mood > 0 && hours > 0 ? [{ mood, hours }] : [];
      });
      const average = (rows: typeof pairs) => rows.length ? rows.reduce((sum, row) => sum + row.mood, 0) / rows.length : null;
      const highMood = average(pairs.filter((row) => row.hours >= 7));
      const lowMood = average(pairs.filter((row) => row.hours < 7));
      const pattern = highMood != null && lowMood != null && lowMood > 0
        ? `Your mood score is ${Math.round(((highMood - lowMood) / lowMood) * 100)}% higher on days after 7+ hours sleep.`
        : "Log more mood and sleep check-ins to unlock pattern insights.";
      return json({ pattern, weekStart: startKey, weekEnd: asDate(new Date(endExclusive.getTime() - 86400000)) });
    }

    if (kind === "weekly-report") {
      const scoreResult = await context.admin
        .from("dad_score_view")
        .select("mind_score,body_score,bond_score,mind_week_change,body_week_change,bond_week_change,recommended_action")
        .eq("user_id", context.userId)
        .maybeSingle();
      if (scoreResult.error) throw scoreResult.error;
      const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString();
      const monthEnd = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)).toISOString();
      const workoutResult = await context.admin.from("workout_sessions")
        .select("id", { count: "exact", head: true })
        .eq("user_id", context.userId).gte("performed_at", monthStart).lt("performed_at", monthEnd);
      if (workoutResult.error) throw workoutResult.error;
      const score = scoreResult.data;
      return json({ report: score ? buildWeeklyReport({
        mindScore: score.mind_score == null ? null : Number(score.mind_score),
        bodyScore: score.body_score == null ? null : Number(score.body_score),
        bondScore: score.bond_score == null ? null : Number(score.bond_score),
        mindWeekChange: score.mind_week_change == null ? null : Number(score.mind_week_change),
        bodyWeekChange: score.body_week_change == null ? null : Number(score.body_week_change),
        bondWeekChange: score.bond_week_change == null ? null : Number(score.bond_week_change),
        monthWorkouts: workoutResult.count ?? 0,
        recommendedAction: score.recommended_action,
      }) : null });
    }

    if (kind === "monthly-report") {
      const monthStart = asDate(new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)));
      const nextMonthStart = asDate(new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)));
      const monthEndTime = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)).toISOString();
      const monthStartTime = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)).toISOString();
      const [workouts, journal, dadDates, sleep, streak, moods] = await Promise.all([
        context.admin.from("workout_sessions").select("id", { count: "exact", head: true }).eq("user_id", context.userId).gte("performed_at", monthStartTime).lt("performed_at", monthEndTime),
        context.admin.from("journal_entries").select("id", { count: "exact", head: true }).eq("user_id", context.userId).gte("created_at", monthStartTime).lt("created_at", monthEndTime),
        context.admin.from("dad_dates").select("id", { count: "exact", head: true }).eq("user_id", context.userId).eq("source", "ai_search"),
        context.admin.from("sleep_logs").select("hours").eq("user_id", context.userId).gte("date", monthStart).lt("date", nextMonthStart),
        context.admin.from("user_streaks").select("streak_count").eq("user_id", context.userId).maybeSingle(),
        context.admin.from("mood_logs").select("mood_value,mood_scale_version").eq("user_id", context.userId).gte("date", monthStart).lt("date", nextMonthStart),
      ]);
      const error = workouts.error ?? journal.error ?? dadDates.error ?? sleep.error ?? streak.error ?? moods.error;
      if (error) throw error;
      const sleepRows = sleep.data ?? [];
      const moodRows = moods.data ?? [];
      const sleepAverage = sleepRows.length ? sleepRows.reduce((sum, row) => sum + Number(row.hours), 0) / sleepRows.length : null;
      const moodAverage = moodRows.length
        ? moodRows.reduce((sum, row) => sum + Number(row.mood_value) + (row.mood_scale_version === 1 ? 0 : 1), 0) / moodRows.length
        : null;
      return json({ report: {
        workouts: workouts.count ?? 0,
        journal: journal.count ?? 0,
        dadDates: dadDates.count ?? 0,
        avgSleep: sleepAverage == null ? null : Math.round(sleepAverage * 10) / 10,
        streak: streak.data?.streak_count ?? 0,
        avgMood: moodAverage == null ? null : moodAverage >= 4.5 ? "Fired up" : moodAverage >= 3.5 ? "Great" : moodAverage >= 2.5 ? "Good" : moodAverage >= 1.5 ? "Okay" : "Stressed",
      } });
    }

    return json({ error: "Unknown insight kind" }, 400);
  } catch (error) {
    console.error("[pro/insights] Failed to build Pro insight", error);
    return json({ error: "Insight unavailable" }, 503);
  }
}
